version: '3'
services:

  db:
    container_name: solokill-db
    image: mysql
    environment:
      MYSQL_DATABASE: solokill
      MYSQL_USERNAME: ${DATASOURCE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
    restart: always

  redis:
    container_name: solokill-redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  app:
    container_name: solokill-app
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - redis
      - db
    environment:
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      API_KEY: ${API_KEY}