FROM openjdk:17-oracle
ARG JAR_FILE_PATH=build/libs/solokill-0.0.1-SNAPSHOT.jar
ENV DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
    DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
    DATASOURCE_URL=${DATASOURCE_URL}
    API_KEY=${API_KEY}
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]