spring:
  config:
    import: optional:file:.env[.properties]

  mail:
    host: ${GOOGLE_MAIL_HOST}
    port: ${GOOGLE_MAIL_PORT}
    username: ${GOOGLE_MAIL_USERNAME}
    password: ${GOOGLE_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  datasource:
    hikari:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${MASTER_DATASOURCE_URL}
        username: ${MASTER_DATASOURCE_USERNAME}
        password: ${MASTER_DATASOURCE_PASSWORD}
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${SLAVE_DATASOURCE_URL}
        username: ${SLAVE_DATASOURCE_USERNAME}
        password: ${SLAVE_DATASOURCE_PASSWORD}

  redis:
    cache:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    session:
      host: ${REDIS_SESSION_HOST}
      port: ${REDIS_SESSION_PORT}


riot-api:
  key: ${API_KEY}
  url:
    kr: https://kr.api.riotgames.com
    asia: https://asia.api.riotgames.com

logging:
  level:
    #    root: debug
    com.geonwoo.solokll.global.client.feign.feignclient.RiotSummonerOpenFeign: debug

email:
  address: ${GOOGLE_MAIL_USERNAME}

fcm:
  certification: ${FCM_PATH}

ncp:
  access-key: ${ACCESS_KEY}
  secret-key: ${SECRET_KEY}
  region-name: "kr-standard"
  object-endpoint: "https://kr.object.ncloudstorage.com"
  bucket-name: "solokill-bucket"
  folder-name: "solokill-folder/"

